import { stringify } from "yaml";
import { createApp, openApiInfo } from "../src/api/app";
import type { AppDependencies } from "../src/api/dependencies";

// Generation never loads env, connects to a DB, or invokes an auth/provider API.
const unused = async (): Promise<never> => {
  throw new Error("Contract generation must not call runtime services.");
};
const dependencies: AppDependencies = {
  progress: { summary: unused, comparison: unused, activity: unused },
  billing: { submit: unused, notification: unused },
  intelligence: { decision: unused, chat: unused },
  sync: { push: unused, pull: unused, acknowledge: unused },
  catalog: unused,
  deleteAccount: unused,
  exportAccount: unused,
  checkDatabase: unused,
  authenticate: unused,
  handleAuth: unused,
  bootstrap: unused,
  trainingPolicy: unused,
  registerDevice: unused,
  revokeDevice: unused,
  entitlements: unused,
};
const document = createApp(dependencies, {
  logging: false,
}).getOpenAPI31Document(openApiInfo);
const target = new URL("../../contracts/openapi.yaml", import.meta.url);
const contents = `# Generated by bun run openapi:generate. Do not edit by hand.\n${stringify(document, { lineWidth: 100 })}`;

if (process.argv.includes("--check")) {
  if (
    !(await Bun.file(target).exists()) ||
    (await Bun.file(target).text()) !== contents
  ) {
    console.error(
      "contracts/openapi.yaml is stale. Run bun run openapi:generate.",
    );
    process.exit(1);
  }
  console.info("OpenAPI contract is up to date.");
} else {
  await Bun.write(target, contents);
  console.info("Generated contracts/openapi.yaml.");
}
